// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/winning-number/fdj-sdk/v2/source"
)

// NewMockAPI creates a new instance of MockAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPI {
	mock := &MockAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPI is an autogenerated mock type for the API type
type MockAPI struct {
	mock.Mock
}

type MockAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPI) EXPECT() *MockAPI_Expecter {
	return &MockAPI_Expecter{mock: &_m.Mock}
}

// DownloadHistory provides a mock function for the type MockAPI
func (_mock *MockAPI) DownloadHistory(ctx context.Context, datasetID string) (source.Source, error) {
	ret := _mock.Called(ctx, datasetID)

	if len(ret) == 0 {
		panic("no return value specified for DownloadHistory")
	}

	var r0 source.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (source.Source, error)); ok {
		return returnFunc(ctx, datasetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) source.Source); ok {
		r0 = returnFunc(ctx, datasetID)
	} else {
		r0 = ret.Get(0).(source.Source)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, datasetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_DownloadHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadHistory'
type MockAPI_DownloadHistory_Call struct {
	*mock.Call
}

// DownloadHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetID string
func (_e *MockAPI_Expecter) DownloadHistory(ctx interface{}, datasetID interface{}) *MockAPI_DownloadHistory_Call {
	return &MockAPI_DownloadHistory_Call{Call: _e.mock.On("DownloadHistory", ctx, datasetID)}
}

func (_c *MockAPI_DownloadHistory_Call) Run(run func(ctx context.Context, datasetID string)) *MockAPI_DownloadHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_DownloadHistory_Call) Return(source1 source.Source, err error) *MockAPI_DownloadHistory_Call {
	_c.Call.Return(source1, err)
	return _c
}

func (_c *MockAPI_DownloadHistory_Call) RunAndReturn(run func(ctx context.Context, datasetID string) (source.Source, error)) *MockAPI_DownloadHistory_Call {
	_c.Call.Return(run)
	return _c
}

// HistoryMetadata provides a mock function for the type MockAPI
func (_mock *MockAPI) HistoryMetadata(ctx context.Context, datasetID string) (source.Metadata, error) {
	ret := _mock.Called(ctx, datasetID)

	if len(ret) == 0 {
		panic("no return value specified for HistoryMetadata")
	}

	var r0 source.Metadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (source.Metadata, error)); ok {
		return returnFunc(ctx, datasetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) source.Metadata); ok {
		r0 = returnFunc(ctx, datasetID)
	} else {
		r0 = ret.Get(0).(source.Metadata)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, datasetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_HistoryMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HistoryMetadata'
type MockAPI_HistoryMetadata_Call struct {
	*mock.Call
}

// HistoryMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetID string
func (_e *MockAPI_Expecter) HistoryMetadata(ctx interface{}, datasetID interface{}) *MockAPI_HistoryMetadata_Call {
	return &MockAPI_HistoryMetadata_Call{Call: _e.mock.On("HistoryMetadata", ctx, datasetID)}
}

func (_c *MockAPI_HistoryMetadata_Call) Run(run func(ctx context.Context, datasetID string)) *MockAPI_HistoryMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_HistoryMetadata_Call) Return(metadata source.Metadata, err error) *MockAPI_HistoryMetadata_Call {
	_c.Call.Return(metadata, err)
	return _c
}

func (_c *MockAPI_HistoryMetadata_Call) RunAndReturn(run func(ctx context.Context, datasetID string) (source.Metadata, error)) *MockAPI_HistoryMetadata_Call {
	_c.Call.Return(run)
	return _c
}
