// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/winning-number/fdj-sdk-lotto"
	"github.com/winning-number/fdj-sdk-lotto/draw"
)

// NewMockAPI creates a new instance of MockAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPI {
	mock := &MockAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPI is an autogenerated mock type for the API type
type MockAPI struct {
	mock.Mock
}

type MockAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPI) EXPECT() *MockAPI_Expecter {
	return &MockAPI_Expecter{mock: &_m.Mock}
}

// DownloadSource provides a mock function for the type MockAPI
func (_mock *MockAPI) DownloadSource(ctx context.Context, path string, source []lotto.SourceInfo) error {
	ret := _mock.Called(ctx, path, source)

	if len(ret) == 0 {
		panic("no return value specified for DownloadSource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []lotto.SourceInfo) error); ok {
		r0 = returnFunc(ctx, path, source)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_DownloadSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadSource'
type MockAPI_DownloadSource_Call struct {
	*mock.Call
}

// DownloadSource is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - source []lotto.SourceInfo
func (_e *MockAPI_Expecter) DownloadSource(ctx interface{}, path interface{}, source interface{}) *MockAPI_DownloadSource_Call {
	return &MockAPI_DownloadSource_Call{Call: _e.mock.On("DownloadSource", ctx, path, source)}
}

func (_c *MockAPI_DownloadSource_Call) Run(run func(ctx context.Context, path string, source []lotto.SourceInfo)) *MockAPI_DownloadSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []lotto.SourceInfo
		if args[2] != nil {
			arg2 = args[2].([]lotto.SourceInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPI_DownloadSource_Call) Return(err error) *MockAPI_DownloadSource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_DownloadSource_Call) RunAndReturn(run func(ctx context.Context, path string, source []lotto.SourceInfo) error) *MockAPI_DownloadSource_Call {
	_c.Call.Return(run)
	return _c
}

// Draws provides a mock function for the type MockAPI
func (_mock *MockAPI) Draws(filter lotto.Filter, order draw.OrderType) []draw.Draw {
	ret := _mock.Called(filter, order)

	if len(ret) == 0 {
		panic("no return value specified for Draws")
	}

	var r0 []draw.Draw
	if returnFunc, ok := ret.Get(0).(func(lotto.Filter, draw.OrderType) []draw.Draw); ok {
		r0 = returnFunc(filter, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]draw.Draw)
		}
	}
	return r0
}

// MockAPI_Draws_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Draws'
type MockAPI_Draws_Call struct {
	*mock.Call
}

// Draws is a helper method to define mock.On call
//   - filter lotto.Filter
//   - order draw.OrderType
func (_e *MockAPI_Expecter) Draws(filter interface{}, order interface{}) *MockAPI_Draws_Call {
	return &MockAPI_Draws_Call{Call: _e.mock.On("Draws", filter, order)}
}

func (_c *MockAPI_Draws_Call) Run(run func(filter lotto.Filter, order draw.OrderType)) *MockAPI_Draws_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lotto.Filter
		if args[0] != nil {
			arg0 = args[0].(lotto.Filter)
		}
		var arg1 draw.OrderType
		if args[1] != nil {
			arg1 = args[1].(draw.OrderType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_Draws_Call) Return(draws []draw.Draw) *MockAPI_Draws_Call {
	_c.Call.Return(draws)
	return _c
}

func (_c *MockAPI_Draws_Call) RunAndReturn(run func(filter lotto.Filter, order draw.OrderType) []draw.Draw) *MockAPI_Draws_Call {
	_c.Call.Return(run)
	return _c
}

// DuplicatedDrawIDs provides a mock function for the type MockAPI
func (_mock *MockAPI) DuplicatedDrawIDs() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DuplicatedDrawIDs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockAPI_DuplicatedDrawIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DuplicatedDrawIDs'
type MockAPI_DuplicatedDrawIDs_Call struct {
	*mock.Call
}

// DuplicatedDrawIDs is a helper method to define mock.On call
func (_e *MockAPI_Expecter) DuplicatedDrawIDs() *MockAPI_DuplicatedDrawIDs_Call {
	return &MockAPI_DuplicatedDrawIDs_Call{Call: _e.mock.On("DuplicatedDrawIDs")}
}

func (_c *MockAPI_DuplicatedDrawIDs_Call) Run(run func()) *MockAPI_DuplicatedDrawIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_DuplicatedDrawIDs_Call) Return(strings []string) *MockAPI_DuplicatedDrawIDs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockAPI_DuplicatedDrawIDs_Call) RunAndReturn(run func() []string) *MockAPI_DuplicatedDrawIDs_Call {
	_c.Call.Return(run)
	return _c
}

// LoadFile provides a mock function for the type MockAPI
func (_mock *MockAPI) LoadFile(path string, source lotto.SourceInfo) error {
	ret := _mock.Called(path, source)

	if len(ret) == 0 {
		panic("no return value specified for LoadFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, lotto.SourceInfo) error); ok {
		r0 = returnFunc(path, source)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_LoadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadFile'
type MockAPI_LoadFile_Call struct {
	*mock.Call
}

// LoadFile is a helper method to define mock.On call
//   - path string
//   - source lotto.SourceInfo
func (_e *MockAPI_Expecter) LoadFile(path interface{}, source interface{}) *MockAPI_LoadFile_Call {
	return &MockAPI_LoadFile_Call{Call: _e.mock.On("LoadFile", path, source)}
}

func (_c *MockAPI_LoadFile_Call) Run(run func(path string, source lotto.SourceInfo)) *MockAPI_LoadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 lotto.SourceInfo
		if args[1] != nil {
			arg1 = args[1].(lotto.SourceInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_LoadFile_Call) Return(err error) *MockAPI_LoadFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_LoadFile_Call) RunAndReturn(run func(path string, source lotto.SourceInfo) error) *MockAPI_LoadFile_Call {
	_c.Call.Return(run)
	return _c
}

// LoadSource provides a mock function for the type MockAPI
func (_mock *MockAPI) LoadSource(ctx context.Context, source []lotto.SourceInfo) error {
	ret := _mock.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for LoadSource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []lotto.SourceInfo) error); ok {
		r0 = returnFunc(ctx, source)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_LoadSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSource'
type MockAPI_LoadSource_Call struct {
	*mock.Call
}

// LoadSource is a helper method to define mock.On call
//   - ctx context.Context
//   - source []lotto.SourceInfo
func (_e *MockAPI_Expecter) LoadSource(ctx interface{}, source interface{}) *MockAPI_LoadSource_Call {
	return &MockAPI_LoadSource_Call{Call: _e.mock.On("LoadSource", ctx, source)}
}

func (_c *MockAPI_LoadSource_Call) Run(run func(ctx context.Context, source []lotto.SourceInfo)) *MockAPI_LoadSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []lotto.SourceInfo
		if args[1] != nil {
			arg1 = args[1].([]lotto.SourceInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_LoadSource_Call) Return(err error) *MockAPI_LoadSource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_LoadSource_Call) RunAndReturn(run func(ctx context.Context, source []lotto.SourceInfo) error) *MockAPI_LoadSource_Call {
	_c.Call.Return(run)
	return _c
}

// NDraws provides a mock function for the type MockAPI
func (_mock *MockAPI) NDraws(filter lotto.Filter) int64 {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for NDraws")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(lotto.Filter) int64); ok {
		r0 = returnFunc(filter)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockAPI_NDraws_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NDraws'
type MockAPI_NDraws_Call struct {
	*mock.Call
}

// NDraws is a helper method to define mock.On call
//   - filter lotto.Filter
func (_e *MockAPI_Expecter) NDraws(filter interface{}) *MockAPI_NDraws_Call {
	return &MockAPI_NDraws_Call{Call: _e.mock.On("NDraws", filter)}
}

func (_c *MockAPI_NDraws_Call) Run(run func(filter lotto.Filter)) *MockAPI_NDraws_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lotto.Filter
		if args[0] != nil {
			arg0 = args[0].(lotto.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAPI_NDraws_Call) Return(n int64) *MockAPI_NDraws_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockAPI_NDraws_Call) RunAndReturn(run func(filter lotto.Filter) int64) *MockAPI_NDraws_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type MockAPI
func (_mock *MockAPI) Reset() {
	_mock.Called()
	return
}

// MockAPI_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockAPI_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *MockAPI_Expecter) Reset() *MockAPI_Reset_Call {
	return &MockAPI_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *MockAPI_Reset_Call) Run(run func()) *MockAPI_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_Reset_Call) Return() *MockAPI_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPI_Reset_Call) RunAndReturn(run func()) *MockAPI_Reset_Call {
	_c.Run(run)
	return _c
}

// SourceUpdatedAt provides a mock function for the type MockAPI
func (_mock *MockAPI) SourceUpdatedAt(ctx context.Context, source lotto.SourceInfo) (time.Time, error) {
	ret := _mock.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for SourceUpdatedAt")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, lotto.SourceInfo) (time.Time, error)); ok {
		return returnFunc(ctx, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, lotto.SourceInfo) time.Time); ok {
		r0 = returnFunc(ctx, source)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, lotto.SourceInfo) error); ok {
		r1 = returnFunc(ctx, source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_SourceUpdatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceUpdatedAt'
type MockAPI_SourceUpdatedAt_Call struct {
	*mock.Call
}

// SourceUpdatedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - source lotto.SourceInfo
func (_e *MockAPI_Expecter) SourceUpdatedAt(ctx interface{}, source interface{}) *MockAPI_SourceUpdatedAt_Call {
	return &MockAPI_SourceUpdatedAt_Call{Call: _e.mock.On("SourceUpdatedAt", ctx, source)}
}

func (_c *MockAPI_SourceUpdatedAt_Call) Run(run func(ctx context.Context, source lotto.SourceInfo)) *MockAPI_SourceUpdatedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 lotto.SourceInfo
		if args[1] != nil {
			arg1 = args[1].(lotto.SourceInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_SourceUpdatedAt_Call) Return(time1 time.Time, err error) *MockAPI_SourceUpdatedAt_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockAPI_SourceUpdatedAt_Call) RunAndReturn(run func(ctx context.Context, source lotto.SourceInfo) (time.Time, error)) *MockAPI_SourceUpdatedAt_Call {
	_c.Call.Return(run)
	return _c
}
